# connect with local db containers
# docker compose -f docker-compose.local.yml up
name: algobuddy-local
services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
      args:
        NEXT_PUBLIC_USER_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_MATCHING_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_QUESTION_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_COLLABORATION_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_PISTON_API_BASE_URL: ${PISTON_API_BASE_URL}
    image: ui:latest
    ports:
      - "3000:3000"
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:latest
    env_file:
      - ./.env.production.local
    ports:
      - "4000:4000"
    networks:
      - algobuddy
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service:latest
    hostname: "user-service"
    env_file:
      - ./.env.production.local
    networks:
      - algobuddy
    depends_on:
      - mongo-init
      - redis
  matching-service:
    build:
      context: .
      dockerfile: matching-service/Dockerfile
    image: matching-service:latest
    hostname: "matching-service"
    env_file:
      - ./.env.production.local
    networks:
      - algobuddy
    depends_on:
      - redis
  question-service:
    build:
      context: .
      dockerfile: question-service/Dockerfile
    image: question-service:latest
    hostname: "question-service"
    env_file:
      - ./.env.production.local
    networks:
      - algobuddy
    depends_on:
      - mongo-init
  collaboration-service:
    build:
      context: .
      dockerfile: collaboration-service/Dockerfile
    image: collaboration-service:latest
    hostname: "collaboration-service"
    env_file:
      - ./.env.production.local
    networks:
      - algobuddy
    depends_on:
      - redis
  redis:
    image: redis:latest
    hostname: "redis"
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - ./db/redis_data_build:/data/db
    networks:
      - algobuddy
  mongo:
    image: mongo
    hostname: "mongo"
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    volumes:
      - ./db/mongo_data_build:/data/db
    networks:
      - algobuddy
  mongo-init:
    image: mongo
    volumes:
      - ./db/config/init-mongo.sh:/init-mongo.sh
    entrypoint: sh /init-mongo.sh
    networks:
      - algobuddy
    depends_on:
      - mongo

networks:
  algobuddy:


volumes:
  redis_data:
  mongo_data:
